### ISSUE TITLE
How to predict for one sentence?

### ISSUE THREAD

**Issue by puppyapple** [thunlp/HATT-Proto-for-Few-Shot-Relation-Classification#11]
Hello, thanks for sharing the code. I'm new to few-shot learning domain. I've successfully applied your implementation to my own dataset of sentence classification. But I'm a little confused for how we do prediction when receiving one sentence?

**Comment by gaotianyu1350** [comment]
For now, few-shot learning (N-way K-shot few-shot learning) is still a toy setting. You have to provide N classes and K instances for each class for prediction. If you want to learn more, please refer to our dataset papers [FewRel 1.0](https://www.aclweb.org/anthology/D18-1514/) and [FewRel 2.0](https://www.aclweb.org/anthology/D19-1649/). Thanks!
