### ISSUE TITLE
where is the mask in  cnn encoder?

### ISSUE THREAD

**Issue by littttttlebird** [thunlp/HATT-Proto-for-Few-Shot-Relation-Classification#12]
Why does the cnn encoder have no mask operation for the padding part in seq_len dim?

**Comment by gaotianyu1350** [comment]
CNN uses a max pooling and ReLU at the end, and padding part is all zero. So it is not necessary to use a mask.

**Comment by littttttlebird** [comment]
the part of padding embedding is zero，but the conv filter bias will not always all to be zero（1， not initiall by zero，2，bp update)，and it may bigger than other normal conv result，so, i think the mask is need。
