### ISSUE TITLE
what's the motivation of embedding divide operation?

### ISSUE THREAD

**Issue by littttttlebird** [thunlp/HATT-Proto-for-Few-Shot-Relation-Classification#13]
`self.word_vec_mat[cur_id] = self.word_vec_mat[cur_id] / np.sqrt(np.sum(self.word_vec_mat[cur_id] ** 2))`
what's the motivation of the operation to divide sqrt(sum(vector))？

**Comment by gaotianyu1350** [comment]
It is to normalize the word embeddings.
