### ISSUE TITLE
缺少test.json

### ISSUE THREAD

**Issue by Chenhao-Leon** [thunlp/HATT-Proto-for-Few-Shot-Relation-Classification#17]
您好，我这边在/data目录下缺失test.json文件导致报错，请问该怎么解决呢

**Comment by gaotianyu1350** [comment]
`test.json`是隐藏测试集，用于在线评测（请参考[FewRel benchmark](https://thunlp.github.io/1/fewrel1.html)）。如果需要本地运行的话，可以用val.json代替test.json，或者修改代码直接使用val.json.

**Comment by Chenhao-Leon** [comment]
非常感谢~
