### ISSUE TITLE
hi, is eval progress online also sampled from the data set with not fix support set as written  in code 

### ISSUE THREAD

**Issue by herbertchen1** [thunlp/HATT-Proto-for-Few-Shot-Relation-Classification#5]
code in data_loader.py   next_batch.

**Comment by gaotianyu1350** [comment]
Yes. During validation and test, we sample support and query sets from the corresponding datasets. Since the number of sample times is very large, evaluation results eventually converge.

**Comment by herbertchen1** [comment]
> Yes. During validation and test, we sample support and query sets from the corresponding datasets. Since the number of sample times is very large, evaluation results eventually converge.
thanks for your reply!
i've found 5 way 5 shot on pure proto network only 86% in the val dataset , is there 3% gap between val and test?

**Comment by gaotianyu1350** [comment]
Yes~
